/**
 * TempApi
 * This is a sample openApi document
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: lampralexandros@gmail.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ProjectProjectImage from './ProjectProjectImage';
import Workpackage from './Workpackage';

/**
 * The Project model module.
 * @module model/Project
 * @version 1.0.0
 */
class Project {
    /**
     * Constructs a new <code>Project</code>.
     * @alias module:model/Project
     * @param projectImage {module:model/ProjectProjectImage} 
     * @param projectTitle {String} 
     * @param projectStartDate {String} 
     * @param projectWebsite {String} 
     * @param projectEndDate {String} 
     * @param projectDuration {String} 
     * @param projectGA {String} 
     * @param projectAbstract {String} 
     * @param projectDescription {String} 
     * @param projectWp {Array.<module:model/Workpackage>} 
     */
    constructor(projectImage, projectTitle, projectStartDate, projectWebsite, projectEndDate, projectDuration, projectGA, projectAbstract, projectDescription, projectWp) { 
        
        Project.initialize(this, projectImage, projectTitle, projectStartDate, projectWebsite, projectEndDate, projectDuration, projectGA, projectAbstract, projectDescription, projectWp);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, projectImage, projectTitle, projectStartDate, projectWebsite, projectEndDate, projectDuration, projectGA, projectAbstract, projectDescription, projectWp) { 
        obj['projectImage'] = projectImage;
        obj['projectTitle'] = projectTitle;
        obj['projectStartDate'] = projectStartDate;
        obj['projectWebsite'] = projectWebsite;
        obj['projectEndDate'] = projectEndDate;
        obj['projectDuration'] = projectDuration;
        obj['projectGA'] = projectGA;
        obj['projectAbstract'] = projectAbstract;
        obj['projectDescription'] = projectDescription;
        obj['projectWp'] = projectWp;
    }

    /**
     * Constructs a <code>Project</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/Project} obj Optional instance to populate.
     * @return {module:model/Project} The populated <code>Project</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new Project();

            if (data.hasOwnProperty('_id')) {
                obj['_id'] = ApiClient.convertToType(data['_id'], 'String');
            }
            if (data.hasOwnProperty('projectImage')) {
                obj['projectImage'] = ProjectProjectImage.constructFromObject(data['projectImage']);
            }
            if (data.hasOwnProperty('projectTitle')) {
                obj['projectTitle'] = ApiClient.convertToType(data['projectTitle'], 'String');
            }
            if (data.hasOwnProperty('projectStartDate')) {
                obj['projectStartDate'] = ApiClient.convertToType(data['projectStartDate'], 'String');
            }
            if (data.hasOwnProperty('projectWebsite')) {
                obj['projectWebsite'] = ApiClient.convertToType(data['projectWebsite'], 'String');
            }
            if (data.hasOwnProperty('projectEndDate')) {
                obj['projectEndDate'] = ApiClient.convertToType(data['projectEndDate'], 'String');
            }
            if (data.hasOwnProperty('projectDuration')) {
                obj['projectDuration'] = ApiClient.convertToType(data['projectDuration'], 'String');
            }
            if (data.hasOwnProperty('projectGA')) {
                obj['projectGA'] = ApiClient.convertToType(data['projectGA'], 'String');
            }
            if (data.hasOwnProperty('projectAbstract')) {
                obj['projectAbstract'] = ApiClient.convertToType(data['projectAbstract'], 'String');
            }
            if (data.hasOwnProperty('projectDescription')) {
                obj['projectDescription'] = ApiClient.convertToType(data['projectDescription'], 'String');
            }
            if (data.hasOwnProperty('projectWp')) {
                obj['projectWp'] = ApiClient.convertToType(data['projectWp'], [Workpackage]);
            }
        }
        return obj;
    }


}

/**
 * @member {String} _id
 */
Project.prototype['_id'] = undefined;

/**
 * @member {module:model/ProjectProjectImage} projectImage
 */
Project.prototype['projectImage'] = undefined;

/**
 * @member {String} projectTitle
 */
Project.prototype['projectTitle'] = undefined;

/**
 * @member {String} projectStartDate
 */
Project.prototype['projectStartDate'] = undefined;

/**
 * @member {String} projectWebsite
 */
Project.prototype['projectWebsite'] = undefined;

/**
 * @member {String} projectEndDate
 */
Project.prototype['projectEndDate'] = undefined;

/**
 * @member {String} projectDuration
 */
Project.prototype['projectDuration'] = undefined;

/**
 * @member {String} projectGA
 */
Project.prototype['projectGA'] = undefined;

/**
 * @member {String} projectAbstract
 */
Project.prototype['projectAbstract'] = undefined;

/**
 * @member {String} projectDescription
 */
Project.prototype['projectDescription'] = undefined;

/**
 * @member {Array.<module:model/Workpackage>} projectWp
 */
Project.prototype['projectWp'] = undefined;






export default Project;

